<?php
if (function_exists('acf_add_local_field_group')) {
	acf_add_local_field_group(array(
		'key' => 'group_5d19aaf9c929e',
		'title' => 'Content Insights for Editors',
		'fields' => array(
			array(
				'key' => 'field_5d19ab0cbbc00',
				'label' => 'Analyserade posttyper',
				'name' => 'analysed_post_types',
				'type' => 'posttype_select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 1,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
			),
			array(
				'key' => 'field_5d19cd83d7edd',
				'label' => 'Använd alternativt användarfält',
				'name' => 'use_alternate_user_field',
				'type' => 'true_false',
				'instructions' =>
					'Använder fältet Redaktör (page_meta_maineditor) för användarfiltrering, istället för Författare som används som standard.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5d19cd83d4ea3',
				'label' => 'Aktivera automatiska utskick för brutna länkar',
				'name' => 'use_broken_links_cron',
				'type' => 'true_false',
				'instructions' =>
					'Skickar mail till alla författare, redaktörer samt administratörer varannan vecka med en rapport om deras brutna länkar.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5d1c8f1232ba5',
				'label' => 'Föråldrade sidor',
				'name' => 'ws_minimum_last_updated_threshold',
				'type' => 'number',
				'instructions' =>
					'Ställ in tröskelvärdet för hur många dagar en sida som ej uppdaterats skall vara innan pluginet flaggar sidan som föråldrad.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'dagar',
				'min' => 5,
				'step' => 1,
			),
			array(
				'key' => 'field_5d1c8cd534387',
				'label' => '<h1>Matomo</h1>',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5d1c8d1235ea1',
				'label' => 'Matomo Api URL',
				'name' => 'matomo_api_url',
				'type' => 'text',
				'instructions' => 'ex. https://analys.dindoman.se/',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5d1c8d2b35ea2',
				'label' => 'Matomo Api key',
				'name' => 'matomo_api_key',
				'type' => 'text',
				'instructions' =>
					'Besök admin för din Matomoinstallation. Under Plattform -> API finns &token_auth=xxxxxxxxxxxxxxx. Klistra in värdet motsvarande xxxxxxxxxxxxxxx',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5d1c8d3e35ea3',
				'label' => 'Matomo id site',
				'name' => 'matomo_id_site',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 1,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'content-insights-for-editors-page-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
}
